import { makeStyles } from '@mui/styles';
import colors from '../../lib/colors';
export default makeStyles((theme) => ({
  container_cart: {
    maxWidth: 1440,
    margin: 'auto auto',
    display: 'flex',
    justifyContent: 'space-between',
  },
  container_left_cart: {
    width: '70%',
  },
  container_right_cart: {
    width: '30%',
  },
  // th_product: {
  //   width: '40%',
  // },
  // th_product: {
  //   width: '15%',
  // },
  tr_table_cart: {
    width: '100%',
    // display: 'flex',
    // justifyContent: 'space-around',
  },
  table_cart: {
    width: '100%',
  },

  container_right_cart: {
    width: '25%',
    border: '1px solid',
    borderColor: colors.lightGray,
    borderRadius: 10,
  },

  head_right_cart: {
    width: '100&',
    height: 40,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: colors.green,
  },
  box_address_ship: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  horizontal_devider: {
    width: '100%',
    height: 1,
    backgroundColor: colors.lightGray,
    marginTop: 16,
    marginBottom: 16,
  },
  box_brand: {
    padding: 8,
  },
  box_item_total_cart: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  btn_total_cart: {
    height: 40,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: colors.orange,
    marginTop: 40,
    borderRadius: 6,
    border: '1px solid',
    color: colors.orange,
    borderColor: colors.orange,
    '&:hover': {
      backgroundColor: colors.orange,
      color: colors.white,
    },
    cursor: 'pointer',
  },
  box_address: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  box_coupon_input: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  box_coupon: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  input_coupon: {
    width: 200,
    height: 40,
    borderRadius: 6,
  },
  btn_apply_coupon: {
    height: 40,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primary,
    color: colors.white,
    borderRadius: 6,
    fontSize: 12,
    width: '100%',
    marginLeft: 8,
    cursor: 'pointer',
  },
  box_coupon_checkout: {
    marginBottom: 16,
  },
  type_pay: {
    marginTop: 24,
  },
  box_radio_type_pay: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  model_edit_address: {
    position: 'absolute',
    top: '25%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 600,
    backgroundColor: colors.white,
    borderRadius: 5,
    padding: 16,
  },
  input_edit_info_account_address: {
    height: 40,
    width: 200,
    marginRight: 16,
    borderRadius: 6,
    marginBottom: 16,
    backgroundColor: colors.white,
  },
  btn_cancle: {
    height: 40,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0px 16px',
    fontSize: 12,
    borderRadius: 6,
    border: '1px solid',
    borderColor: colors.orange,
    backgroundColor: colors.orange,
    color: colors.white,
    cursor: 'pointer',
    marginRight: 8,
  },
  btn_save: {
    height: 40,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0px 16px',
    fontSize: 12,
    borderRadius: 6,
    border: '1px solid',
    borderColor: colors.green,
    backgroundColor: colors.green,
    color: colors.white,
    cursor: 'pointer',
  },

  box_btn: {
    display: 'flex',
    justifyContent: 'flex-end',
  },
}));
