import { makeStyles } from '@mui/styles';
import { height } from '@mui/system';
import colors from '../../lib/colors';
export default makeStyles((theme) => ({
  bx_container_qa: {
    position: 'absolute',
    zIndex: 999,
    right: 0,
    top: 300,
    boxShadow: '0 1px 15px 0 rgb(0 0 0 / 10%)',
    width: 100,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 50,
  },
  bx_container_vd: {
    position: 'absolute',
    zIndex: 999,
    right: 0,
    top: 390,
    boxShadow: '0 1px 15px 0 rgb(0 0 0 / 10%)',
    width: 100,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 50,
  },
  bx_container_sw: {
    position: 'absolute',
    zIndex: 999,
    right: 0,
    top: 480,
    boxShadow: '0 1px 15px 0 rgb(0 0 0 / 10%)',
    width: 100,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 50,
  },
  bx_curcle: {
    position: 'absolute',
    width: 60,
    height: 60,
    // border: `2px dashed ${colors.orange}`,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    marginLeft: 5,
    cursor: 'pointer',
  },
  bx_curcle_mask: {
    position: 'absolute',
    width: 60,
    height: 60,
    border: `2px dashed ${colors.orange}`,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 50,
    marginLeft: 5,
    transition: '4s',

    cursor: 'pointer',
    '&:hover': {
      transform: 'rotate(1300deg)',
    },
  },
}));
