// lấy toàn bộ danh sách người dùng

export const START_QUERY = 'START_QUERY';
export const END_QUERY = 'END_QUERY';

export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_FAIL = 'LOGIN_ACCOUNT_FAIL';

export const LOGOUT_ACCOUNT_SUCCESS = 'LOGOUT_ACCOUNT_SUCCESS';
export const LOGOUT_ACCOUNT_FAIL = 'LOGOUT_ACCOUNT_FAIL';

export const GET_ALL_ACCOUNT_SUCCESS = 'GET_ALL_ACCOUNT_SUCCESS';
export const GET_ALL_ACCOUNT_FAIL = 'GET_ALL_ACCOUNT_FAIL';

export const GET_ACCOUNT_PAGE_SUCCESS = 'GET_ACCOUNT_PAGE_SUCCESS';
export const GET_ACCOUNT_PAGE_FAIL = 'GET_ACCOUNT_PAGE_FAIL';
export const GET_ACCOUNT_DETAIL_SUCCESS = 'GET_ACCOUNT_DETAIL_SUCCESS';
export const GET_ACCOUNT_DETAIL_FAIL = 'GET_ACCOUNT_DETAIL_FAIL';
export const SEARCH_ACCOUNT_SUCCESS = 'SEARCH_ACCOUNT_SUCCESS';
export const SEARCH_ACCOUNT_FAIL = 'SEARCH_ACCOUNT_FAIL';
export const POST_ACCOUNT_SUCCESS = 'POST_ACCOUNT_SUCCESS';
export const POST_ACCOUNT_FAIL = 'POST_ACCOUNT_FAIL';
export const PUT_ACCOUNT_SUCCESS = 'PUT_ACCOUNT_SUCCESS';
export const PUT_ACCOUNT_FAIL = 'PUT_ACCOUNT_FAIL';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const PUT_ACCOUNT_VOUCHER_SUCCESS = 'PUT_ACCOUNT_VOUCHER_SUCCESS';
export const PUT_ACCOUNT_VOUCHER_FAIL = 'PUT_ACCOUNT_VOUCHER_FAIL';
