// lấy toàn bộ danh sách người dùng

export const GET_ALL_AFFILATESHOP_SUCCESS = 'GET_ALL_AFFILATESHOP_SUCCESS';
export const GET_ALL_AFFILATESHOP_FAIL = 'GET_ALL_AFFILATESHOP_FAIL';
export const GET_ALL_AFFILATESHOP_ADMIN_SUCCESS =
  'GET_ALL_AFFILATESHOP_ADMIN_SUCCESS';
export const GET_ALL_AFFILATESHOP_ADMIN_FAIL =
  'GET_ALL_AFFILATESHOP_ADMIN_FAIL';
export const GET_ALL_AFFILATESHOP_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_AFFILATESHOP_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_AFFILATESHOP_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_AFFILATESHOP_ADMIN_ACCOUNT_FAIL';
export const GET_AFFILATESHOP_PAGE_SUCCESS = 'GET_AFFILATESHOP_PAGE_SUCCESS';
export const GET_AFFILATESHOP_PAGE_FAIL = 'GET_AFFILATESHOP_PAGE_FAIL';
export const GET_AFFILATESHOP_DETAIL_SUCCESS =
  'GET_AFFILATESHOP_DETAIL_SUCCESS';
export const GET_AFFILATESHOP_DETAIL_FAIL = 'GET_AFFILATESHOP_DETAIL_FAIL';
export const SEARCH_AFFILATESHOP_SUCCESS = 'SEARCH_AFFILATESHOP_SUCCESS';
export const SEARCH_AFFILATESHOP_FAIL = 'SEARCH_AFFILATESHOP_FAIL';
export const POST_AFFILATESHOP_SUCCESS = 'POST_AFFILATESHOP_SUCCESS';
export const POST_AFFILATESHOP_FAIL = 'POST_AFFILATESHOP_FAIL';
export const PUT_AFFILATESHOP_SUCCESS = 'PUT_AFFILATESHOP_SUCCESS';
export const PUT_AFFILATESHOP_FAIL = 'PUT_AFFILATESHOP_FAIL';
export const DELETE_AFFILATESHOP_SUCCESS = 'DELETE_AFFILATESHOP_SUCCESS';
export const DELETE_AFFILATESHOP_FAIL = 'DELETE_AFFILATESHOP_FAIL';
export const CLOSE_AFFILATESHOP = 'CLOSE_AFFILATESHOP';
