// lấy toàn bộ danh sách người dùng

export const GET_ALL_BANNER_SUCCESS = 'GET_ALL_BANNER_SUCCESS';
export const GET_ALL_BANNER_FAIL = 'GET_ALL_BANNER_FAIL';
export const GET_ALL_BANNER_ADMIN_SUCCESS = 'GET_ALL_BANNER_ADMIN_SUCCESS';
export const GET_ALL_BANNER_ADMIN_FAIL = 'GET_ALL_BANNER_ADMIN_FAIL';
export const GET_ALL_BANNER_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_BANNER_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_BANNER_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_BANNER_ADMIN_ACCOUNT_FAIL';
export const GET_BANNER_PAGE_SUCCESS = 'GET_BANNER_PAGE_SUCCESS';
export const GET_BANNER_PAGE_FAIL = 'GET_BANNER_PAGE_FAIL';
export const GET_BANNER_DETAIL_SUCCESS = 'GET_BANNER_DETAIL_SUCCESS';
export const GET_BANNER_DETAIL_FAIL = 'GET_BANNER_DETAIL_FAIL';
export const SEARCH_BANNER_SUCCESS = 'SEARCH_BANNER_SUCCESS';
export const SEARCH_BANNER_FAIL = 'SEARCH_BANNER_FAIL';
export const POST_BANNER_SUCCESS = 'POST_BANNER_SUCCESS';
export const POST_BANNER_FAIL = 'POST_BANNER_FAIL';
export const PUT_BANNER_SUCCESS = 'PUT_BANNER_SUCCESS';
export const PUT_BANNER_FAIL = 'PUT_BANNER_FAIL';
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS';
export const DELETE_BANNER_FAIL = 'DELETE_BANNER_FAIL';
export const CLOSE_BANNER = 'CLOSE_BANNER';
