// lấy toàn bộ danh sách người dùng

export const GET_ALL_BRAND_SUCCESS = 'GET_ALL_BRAND_SUCCESS';
export const GET_ALL_BRAND_FAIL = 'GET_ALL_BRAND_FAIL';
export const GET_ALL_BRAND_ADMIN_SUCCESS = 'GET_ALL_BRAND_ADMIN_SUCCESS';
export const GET_ALL_BRAND_ADMIN_FAIL = 'GET_ALL_BRAND_ADMIN_FAIL';
export const GET_ALL_BRAND_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_BRAND_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_BRAND_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_BRAND_ADMIN_ACCOUNT_FAIL';
export const GET_BRAND_PAGE_SUCCESS = 'GET_BRAND_PAGE_SUCCESS';
export const GET_BRAND_PAGE_FAIL = 'GET_BRAND_PAGE_FAIL';
export const GET_BRAND_DETAIL_SUCCESS = 'GET_BRAND_DETAIL_SUCCESS';
export const GET_BRAND_DETAIL_FAIL = 'GET_BRAND_DETAIL_FAIL';
export const SEARCH_BRAND_SUCCESS = 'SEARCH_BRAND_SUCCESS';
export const SEARCH_BRAND_FAIL = 'SEARCH_BRAND_FAIL';
export const POST_BRAND_SUCCESS = 'POST_BRAND_SUCCESS';
export const POST_BRAND_FAIL = 'POST_BRAND_FAIL';
export const PUT_BRAND_SUCCESS = 'PUT_BRAND_SUCCESS';
export const PUT_BRAND_FAIL = 'PUT_BRAND_FAIL';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAIL = 'DELETE_BRAND_FAIL';
export const CLOSE_BRAND = 'CLOSE_BRAND';
