// lấy toàn bộ danh sách người dùng

export const START_QUERY = 'START_QUERY';
export const END_QUERY = 'END_QUERY';

export const GET_ALL_CART_SUCCESS = 'GET_ALL_CART_SUCCESS';
export const GET_ALL_CART_FAIL = 'GET_ALL_CART_FAIL';
export const GET_ALL_CART_ADMIN_SUCCESS = 'GET_ALL_CART_ADMIN_SUCCESS';
export const GET_ALL_CART_ADMIN_FAIL = 'GET_ALL_CART_ADMIN_FAIL';
export const GET_ALL_CART_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_CART_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_CART_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_CART_ADMIN_ACCOUNT_FAIL';
export const GET_CART_PAGE_SUCCESS = 'GET_CART_PAGE_SUCCESS';
export const GET_CART_PAGE_FAIL = 'GET_CART_PAGE_FAIL';
export const GET_CART_DETAIL_SUCCESS = 'GET_CART_DETAIL_SUCCESS';
export const GET_CART_DETAIL_FAIL = 'GET_CART_DETAIL_FAIL';
export const SEARCH_CART_SUCCESS = 'SEARCH_CART_SUCCESS';
export const SEARCH_CART_FAIL = 'SEARCH_CART_FAIL';
export const POST_CART_SUCCESS = 'POST_CART_SUCCESS';
export const POST_CART_FAIL = 'POST_CART_FAIL';
export const PUT_CART_SUCCESS = 'PUT_CART_SUCCESS';
export const PUT_CART_FAIL = 'PUT_CART_FAIL';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAIL = 'DELETE_CART_FAIL';
export const CLOSE_CART = 'CLOSE_CART';
