// lấy toàn bộ danh sách người dùng

export const START_QUERY = 'START_QUERY';
export const END_QUERY = 'END_QUERY';

export const GET_ALL_CARTITEM_SUCCESS = 'GET_ALL_CARTITEM_SUCCESS';
export const GET_ALL_CARTITEM_FAIL = 'GET_ALL_CARTITEM_FAIL';
export const GET_ALL_CARTITEM_ADMIN_SUCCESS = 'GET_ALL_CARTITEM_ADMIN_SUCCESS';
export const GET_ALL_CARTITEM_ADMIN_FAIL = 'GET_ALL_CARTITEM_ADMIN_FAIL';
export const GET_ALL_CARTITEM_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_CARTITEM_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_CARTITEM_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_CARTITEM_ADMIN_ACCOUNT_FAIL';
export const GET_CARTITEM_PAGE_SUCCESS = 'GET_CARTITEM_PAGE_SUCCESS';
export const GET_CARTITEM_PAGE_FAIL = 'GET_CARTITEM_PAGE_FAIL';
export const GET_CARTITEM_DETAIL_SUCCESS = 'GET_CARTITEM_DETAIL_SUCCESS';
export const GET_CARTITEM_DETAIL_FAIL = 'GET_CARTITEM_DETAIL_FAIL';
export const SEARCH_CARTITEM_SUCCESS = 'SEARCH_CARTITEM_SUCCESS';
export const SEARCH_CARTITEM_FAIL = 'SEARCH_CARTITEM_FAIL';
export const POST_CARTITEM_SUCCESS = 'POST_CARTITEM_SUCCESS';
export const POST_CARTITEM_FAIL = 'POST_CARTITEM_FAIL';
export const PUT_CARTITEM_SUCCESS = 'PUT_CARTITEM_SUCCESS';
export const PUT_CARTITEM_FAIL = 'PUT_CARTITEM_FAIL';
export const DELETE_CARTITEM_SUCCESS = 'DELETE_CARTITEM_SUCCESS';
export const DELETE_CARTITEM_FAIL = 'DELETE_CARTITEM_FAIL';
export const CLOSE_CARTITEM = 'CLOSE_CARTITEM';
