// lấy toàn bộ danh sách người dùng

export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAIL = 'GET_ALL_CATEGORY_FAIL';
export const GET_ALL_CATEGORY_ADMIN_SUCCESS = 'GET_ALL_CATEGORY_ADMIN_SUCCESS';
export const GET_ALL_CATEGORY_ADMIN_FAIL = 'GET_ALL_CATEGORY_ADMIN_FAIL';
export const GET_ALL_CATEGORY_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_CATEGORY_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_CATEGORY_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_CATEGORY_ADMIN_ACCOUNT_FAIL';
export const GET_CATEGORY_PAGE_SUCCESS = 'GET_CATEGORY_PAGE_SUCCESS';
export const GET_CATEGORY_PAGE_FAIL = 'GET_CATEGORY_PAGE_FAIL';
export const GET_CATEGORY_DETAIL_SUCCESS = 'GET_CATEGORY_DETAIL_SUCCESS';
export const GET_CATEGORY_DETAIL_FAIL = 'GET_CATEGORY_DETAIL_FAIL';
export const SEARCH_CATEGORY_SUCCESS = 'SEARCH_CATEGORY_SUCCESS';
export const SEARCH_CATEGORY_FAIL = 'SEARCH_CATEGORY_FAIL';
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_FAIL = 'POST_CATEGORY_FAIL';
export const PUT_CATEGORY_SUCCESS = 'PUT_CATEGORY_SUCCESS';
export const PUT_CATEGORY_FAIL = 'PUT_CATEGORY_FAIL';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';
export const CLOSE_CATEGORY = 'CLOSE_CATEGORY';
