// lấy toàn bộ danh sách người dùng

export const GET_ALL_COLOR_SUCCESS = 'GET_ALL_COLOR_SUCCESS';
export const GET_ALL_COLOR_FAIL = 'GET_ALL_COLOR_FAIL';
export const GET_ALL_COLOR_ADMIN_SUCCESS = 'GET_ALL_COLOR_ADMIN_SUCCESS';
export const GET_ALL_COLOR_ADMIN_FAIL = 'GET_ALL_COLOR_ADMIN_FAIL';
export const GET_ALL_COLOR_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_COLOR_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_COLOR_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_COLOR_ADMIN_ACCOUNT_FAIL';
export const GET_COLOR_PAGE_SUCCESS = 'GET_COLOR_PAGE_SUCCESS';
export const GET_COLOR_PAGE_FAIL = 'GET_COLOR_PAGE_FAIL';
export const GET_COLOR_DETAIL_SUCCESS = 'GET_COLOR_DETAIL_SUCCESS';
export const GET_COLOR_DETAIL_FAIL = 'GET_COLOR_DETAIL_FAIL';
export const SEARCH_COLOR_SUCCESS = 'SEARCH_COLOR_SUCCESS';
export const SEARCH_COLOR_FAIL = 'SEARCH_COLOR_FAIL';
export const POST_COLOR_SUCCESS = 'POST_COLOR_SUCCESS';
export const POST_COLOR_FAIL = 'POST_COLOR_FAIL';
export const PUT_COLOR_SUCCESS = 'PUT_COLOR_SUCCESS';
export const PUT_COLOR_FAIL = 'PUT_COLOR_FAIL';
export const DELETE_COLOR_SUCCESS = 'DELETE_COLOR_SUCCESS';
export const DELETE_COLOR_FAIL = 'DELETE_COLOR_FAIL';
export const CLOSE_COLOR = 'CLOSE_COLOR';
