// lấy toàn bộ danh sách người dùng
export const START_QUERY = 'START_QUERY';
export const END_QUERY = 'END_QUERY';

export const GET_ALL_COMMENT_SUCCESS = 'GET_ALL_COMMENT_SUCCESS';
export const GET_ALL_COMMENT_FAIL = 'GET_ALL_COMMENT_FAIL';
export const GET_ALL_COMMENT_ADMIN_SUCCESS = 'GET_ALL_COMMENT_ADMIN_SUCCESS';
export const GET_ALL_COMMENT_ADMIN_FAIL = 'GET_ALL_COMMENT_ADMIN_FAIL';
export const GET_ALL_COMMENT_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_COMMENT_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_COMMENT_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_COMMENT_ADMIN_ACCOUNT_FAIL';
export const GET_COMMENT_PAGE_SUCCESS = 'GET_COMMENT_PAGE_SUCCESS';
export const GET_COMMENT_PAGE_FAIL = 'GET_COMMENT_PAGE_FAIL';
export const GET_COMMENT_DETAIL_SUCCESS = 'GET_COMMENT_DETAIL_SUCCESS';
export const GET_COMMENT_DETAIL_FAIL = 'GET_COMMENT_DETAIL_FAIL';
export const SEARCH_COMMENT_SUCCESS = 'SEARCH_COMMENT_SUCCESS';
export const SEARCH_COMMENT_FAIL = 'SEARCH_COMMENT_FAIL';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';
export const PUT_COMMENT_SUCCESS = 'PUT_COMMENT_SUCCESS';
export const PUT_COMMENT_FAIL = 'PUT_COMMENT_FAIL';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
export const CLOSE_COMMENT = 'CLOSE_COMMENT';
