// lấy toàn bộ danh sách người dùng

export const GET_ALL_EVENT_SUCCESS = 'GET_ALL_EVENT_SUCCESS';
export const GET_ALL_EVENT_FAIL = 'GET_ALL_EVENT_FAIL';
export const GET_ALL_EVENT_ADMIN_SUCCESS = 'GET_ALL_EVENT_ADMIN_SUCCESS';
export const GET_ALL_EVENT_ADMIN_FAIL = 'GET_ALL_EVENT_ADMIN_FAIL';
export const GET_ALL_EVENT_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_EVENT_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_EVENT_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_EVENT_ADMIN_ACCOUNT_FAIL';
export const GET_EVENT_PAGE_SUCCESS = 'GET_EVENT_PAGE_SUCCESS';
export const GET_EVENT_PAGE_FAIL = 'GET_EVENT_PAGE_FAIL';
export const GET_EVENT_DETAIL_SUCCESS = 'GET_EVENT_DETAIL_SUCCESS';
export const GET_EVENT_DETAIL_FAIL = 'GET_EVENT_DETAIL_FAIL';
export const SEARCH_EVENT_SUCCESS = 'SEARCH_EVENT_SUCCESS';
export const SEARCH_EVENT_FAIL = 'SEARCH_EVENT_FAIL';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_FAIL = 'POST_EVENT_FAIL';
export const PUT_EVENT_SUCCESS = 'PUT_EVENT_SUCCESS';
export const PUT_EVENT_FAIL = 'PUT_EVENT_FAIL';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';
export const CLOSE_EVENT = 'CLOSE_EVENT';
