// lấy toàn bộ danh sách người dùng
export const START_QUERY = 'START_QUERY';
export const END_QUERY = 'END_QUERY';

export const GET_ALL_NOTIFICATION_SUCCESS = 'GET_ALL_NOTIFICATION_SUCCESS';
export const GET_ALL_NOTIFICATION_FAIL = 'GET_ALL_NOTIFICATION_FAIL';
export const GET_ALL_NOTIFICATION_ADMIN_SUCCESS =
  'GET_ALL_NOTIFICATION_ADMIN_SUCCESS';
export const GET_ALL_NOTIFICATION_ADMIN_FAIL =
  'GET_ALL_NOTIFICATION_ADMIN_FAIL';
export const GET_ALL_NOTIFICATION_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_NOTIFICATION_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_NOTIFICATION_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_NOTIFICATION_ADMIN_ACCOUNT_FAIL';
export const GET_NOTIFICATION_PAGE_SUCCESS = 'GET_NOTIFICATION_PAGE_SUCCESS';
export const GET_NOTIFICATION_PAGE_FAIL = 'GET_NOTIFICATION_PAGE_FAIL';
export const GET_NOTIFICATION_DETAIL_SUCCESS =
  'GET_NOTIFICATION_DETAIL_SUCCESS';
export const GET_NOTIFICATION_DETAIL_FAIL = 'GET_NOTIFICATION_DETAIL_FAIL';
export const SEARCH_NOTIFICATION_SUCCESS = 'SEARCH_NOTIFICATION_SUCCESS';
export const SEARCH_NOTIFICATION_FAIL = 'SEARCH_NOTIFICATION_FAIL';
export const POST_NOTIFICATION_SUCCESS = 'POST_NOTIFICATION_SUCCESS';
export const POST_NOTIFICATION_FAIL = 'POST_NOTIFICATION_FAIL';
export const PUT_NOTIFICATION_SUCCESS = 'PUT_NOTIFICATION_SUCCESS';
export const PUT_NOTIFICATION_FAIL = 'PUT_NOTIFICATION_FAIL';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAIL = 'DELETE_NOTIFICATION_FAIL';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
