// lấy toàn bộ danh sách người dùng

export const START_QUERY = 'START_QUERY';
export const END_QUERY = 'END_QUERY';

export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS';
export const GET_ALL_ORDER_FAIL = 'GET_ALL_ORDER_FAIL';
export const GET_ALL_ORDER_ADMIN_SUCCESS = 'GET_ALL_ORDER_ADMIN_SUCCESS';
export const GET_ALL_ORDER_ADMIN_FAIL = 'GET_ALL_ORDER_ADMIN_FAIL';
export const GET_ALL_ORDER_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_ORDER_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_ORDER_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_ORDER_ADMIN_ACCOUNT_FAIL';
export const GET_ORDER_PAGE_SUCCESS = 'GET_ORDER_PAGE_SUCCESS';
export const GET_ORDER_PAGE_FAIL = 'GET_ORDER_PAGE_FAIL';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';
export const SEARCH_ORDER_SUCCESS = 'SEARCH_ORDER_SUCCESS';
export const SEARCH_ORDER_FAIL = 'SEARCH_ORDER_FAIL';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAIL = 'POST_ORDER_FAIL';
export const PUT_ORDER_SUCCESS = 'PUT_ORDER_SUCCESS';
export const PUT_ORDER_FAIL = 'PUT_ORDER_FAIL';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';
export const CLOSE_ORDER = 'CLOSE_ORDER';

export const PUT_CANCEL_ORDER_FAIL = 'PUT_CANCEL_ORDER_FAIL';
export const PUT_CANCEL_ORDER_SUCCESS = 'PUT_CANCEL_ORDER_SUCCESS';
