// lấy toàn bộ danh sách người dùng

export const GET_ALL_PAYMENT_SUCCESS = 'GET_ALL_PAYMENT_SUCCESS';
export const GET_ALL_PAYMENT_FAIL = 'GET_ALL_PAYMENT_FAIL';
export const GET_ALL_PAYMENT_ADMIN_SUCCESS = 'GET_ALL_PAYMENT_ADMIN_SUCCESS';
export const GET_ALL_PAYMENT_ADMIN_FAIL = 'GET_ALL_PAYMENT_ADMIN_FAIL';
export const GET_ALL_PAYMENT_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_PAYMENT_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_PAYMENT_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_PAYMENT_ADMIN_ACCOUNT_FAIL';
export const GET_PAYMENT_PAGE_SUCCESS = 'GET_PAYMENT_PAGE_SUCCESS';
export const GET_PAYMENT_PAGE_FAIL = 'GET_PAYMENT_PAGE_FAIL';
export const GET_PAYMENT_DETAIL_SUCCESS = 'GET_PAYMENT_DETAIL_SUCCESS';
export const GET_PAYMENT_DETAIL_FAIL = 'GET_PAYMENT_DETAIL_FAIL';
export const SEARCH_PAYMENT_SUCCESS = 'SEARCH_PAYMENT_SUCCESS';
export const SEARCH_PAYMENT_FAIL = 'SEARCH_PAYMENT_FAIL';
export const POST_PAYMENT_SUCCESS = 'POST_PAYMENT_SUCCESS';
export const POST_PAYMENT_FAIL = 'POST_PAYMENT_FAIL';
export const PUT_PAYMENT_SUCCESS = 'PUT_PAYMENT_SUCCESS';
export const PUT_PAYMENT_FAIL = 'PUT_PAYMENT_FAIL';
export const DELETE_PAYMENT_SUCCESS = 'DELETE_PAYMENT_SUCCESS';
export const DELETE_PAYMENT_FAIL = 'DELETE_PAYMENT_FAIL';
export const CLOSE_PAYMENT = 'CLOSE_PAYMENT';
