// lấy toàn bộ danh sách người dùng

export const GET_ALL_POSITION_SUCCESS = 'GET_ALL_POSITION_SUCCESS';
export const GET_ALL_POSITION_FAIL = 'GET_ALL_POSITION_FAIL';
export const GET_ALL_POSITION_ADMIN_SUCCESS = 'GET_ALL_POSITION_ADMIN_SUCCESS';
export const GET_ALL_POSITION_ADMIN_FAIL = 'GET_ALL_POSITION_ADMIN_FAIL';
export const GET_ALL_POSITION_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_POSITION_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_POSITION_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_POSITION_ADMIN_ACCOUNT_FAIL';
export const GET_POSITION_PAGE_SUCCESS = 'GET_POSITION_PAGE_SUCCESS';
export const GET_POSITION_PAGE_FAIL = 'GET_POSITION_PAGE_FAIL';
export const GET_POSITION_DETAIL_SUCCESS = 'GET_POSITION_DETAIL_SUCCESS';
export const GET_POSITION_DETAIL_FAIL = 'GET_POSITION_DETAIL_FAIL';
export const SEARCH_POSITION_SUCCESS = 'SEARCH_POSITION_SUCCESS';
export const SEARCH_POSITION_FAIL = 'SEARCH_POSITION_FAIL';
export const POST_POSITION_SUCCESS = 'POST_POSITION_SUCCESS';
export const POST_POSITION_FAIL = 'POST_POSITION_FAIL';
export const PUT_POSITION_SUCCESS = 'PUT_POSITION_SUCCESS';
export const PUT_POSITION_FAIL = 'PUT_POSITION_FAIL';
export const DELETE_POSITION_SUCCESS = 'DELETE_POSITION_SUCCESS';
export const DELETE_POSITION_FAIL = 'DELETE_POSITION_FAIL';
export const CLOSE_POSITION = 'CLOSE_POSITION';
