// lấy toàn bộ danh sách người dùng
export const START_QUERY = 'START_QUERY';
export const END_QUERY = 'END_QUERY';

export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS';
export const GET_ALL_PRODUCT_FAIL = 'GET_ALL_PRODUCT_FAIL';
export const GET_ALL_PRODUCT_ADMIN_SUCCESS = 'GET_ALL_PRODUCT_ADMIN_SUCCESS';
export const GET_ALL_PRODUCT_ADMIN_FAIL = 'GET_ALL_PRODUCT_ADMIN_FAIL';
export const GET_ALL_PRODUCT_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_PRODUCT_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_PRODUCT_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_PRODUCT_ADMIN_ACCOUNT_FAIL';
export const GET_PRODUCT_PAGE_SUCCESS = 'GET_PRODUCT_PAGE_SUCCESS';
export const GET_PRODUCT_PAGE_FAIL = 'GET_PRODUCT_PAGE_FAIL';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCT_DETAIL_FAIL';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_FAIL = 'SEARCH_PRODUCT_FAIL';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_FAIL = 'POST_PRODUCT_FAIL';
export const PUT_PRODUCT_SUCCESS = 'PUT_PRODUCT_SUCCESS';
export const PUT_PRODUCT_FAIL = 'PUT_PRODUCT_FAIL';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const CLOSE_PRODUCT = 'CLOSE_PRODUCT';

export const GET_ALL_PRODUCT_CATEGORY_SUCCESS =
  'GET_ALL_PRODUCT_CATEGORY_SUCCESS';
export const GET_ALL_PRODUCT_CATEGORY_FAIL = 'GET_ALL_PRODUCT_CATEGORY_FAIL';
export const GET_ALL_PRODUCT_TOP_SALE_SUCCESS =
  'GET_ALL_PRODUCT_TOP_SALE_SUCCESS';
export const GET_ALL_PRODUCT_TOP_SALE_FAIL = 'GET_ALL_PRODUCT_TOP_SALE_FAIL';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';
