// lấy toàn bộ danh sách người dùng

export const GET_ALL_SIZE_SUCCESS = 'GET_ALL_SIZE_SUCCESS';
export const GET_ALL_SIZE_FAIL = 'GET_ALL_SIZE_FAIL';
export const GET_ALL_SIZE_ADMIN_SUCCESS = 'GET_ALL_SIZE_ADMIN_SUCCESS';
export const GET_ALL_SIZE_ADMIN_FAIL = 'GET_ALL_SIZE_ADMIN_FAIL';
export const GET_ALL_SIZE_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_SIZE_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_SIZE_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_SIZE_ADMIN_ACCOUNT_FAIL';
export const GET_SIZE_PAGE_SUCCESS = 'GET_SIZE_PAGE_SUCCESS';
export const GET_SIZE_PAGE_FAIL = 'GET_SIZE_PAGE_FAIL';
export const GET_SIZE_DETAIL_SUCCESS = 'GET_SIZE_DETAIL_SUCCESS';
export const GET_SIZE_DETAIL_FAIL = 'GET_SIZE_DETAIL_FAIL';
export const SEARCH_SIZE_SUCCESS = 'SEARCH_SIZE_SUCCESS';
export const SEARCH_SIZE_FAIL = 'SEARCH_SIZE_FAIL';
export const POST_SIZE_SUCCESS = 'POST_SIZE_SUCCESS';
export const POST_SIZE_FAIL = 'POST_SIZE_FAIL';
export const PUT_SIZE_SUCCESS = 'PUT_SIZE_SUCCESS';
export const PUT_SIZE_FAIL = 'PUT_SIZE_FAIL';
export const DELETE_SIZE_SUCCESS = 'DELETE_SIZE_SUCCESS';
export const DELETE_SIZE_FAIL = 'DELETE_SIZE_FAIL';
export const CLOSE_SIZE = 'CLOSE_SIZE';
