// lấy toàn bộ danh sách người dùng

export const GET_ALL_TEAM_SUCCESS = 'GET_ALL_TEAM_SUCCESS';
export const GET_ALL_TEAM_FAIL = 'GET_ALL_TEAM_FAIL';
export const GET_ALL_TEAM_ADMIN_SUCCESS = 'GET_ALL_TEAM_ADMIN_SUCCESS';
export const GET_ALL_TEAM_ADMIN_FAIL = 'GET_ALL_TEAM_ADMIN_FAIL';
export const GET_ALL_TEAM_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_TEAM_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_TEAM_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_TEAM_ADMIN_ACCOUNT_FAIL';
export const GET_TEAM_PAGE_SUCCESS = 'GET_TEAM_PAGE_SUCCESS';
export const GET_TEAM_PAGE_FAIL = 'GET_TEAM_PAGE_FAIL';
export const GET_TEAM_DETAIL_SUCCESS = 'GET_TEAM_DETAIL_SUCCESS';
export const GET_TEAM_DETAIL_FAIL = 'GET_TEAM_DETAIL_FAIL';
export const SEARCH_TEAM_SUCCESS = 'SEARCH_TEAM_SUCCESS';
export const SEARCH_TEAM_FAIL = 'SEARCH_TEAM_FAIL';
export const POST_TEAM_SUCCESS = 'POST_TEAM_SUCCESS';
export const POST_TEAM_FAIL = 'POST_TEAM_FAIL';
export const PUT_TEAM_SUCCESS = 'PUT_TEAM_SUCCESS';
export const PUT_TEAM_FAIL = 'PUT_TEAM_FAIL';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAIL = 'DELETE_TEAM_FAIL';
export const CLOSE_TEAM = 'CLOSE_TEAM';
