export const SET_NOTE = 'SET_NOTE';
export const SET_LEANGUAGE = 'SET_LEANGUAGE';

export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS';
export const GET_PROVINCE_FAIL = 'GET_PROVINCE_FAIL';
export const GET_DISTRICT_SUCCESS = 'GET_DISTRICT_SUCCESS';
export const GET_DISTRICT_FAIL = 'GET_DISTRICT_FAIL';
export const GET_WARD_SUCCESS = 'GET_WARD_SUCCESS';
export const GET_WARD_FAIL = 'GET_WARD_FAIL';
