// lấy toàn bộ danh sách người dùng

export const GET_ALL_VOUCHER_SUCCESS = 'GET_ALL_VOUCHER_SUCCESS';
export const GET_ALL_VOUCHER_FAIL = 'GET_ALL_VOUCHER_FAIL';
export const GET_ALL_VOUCHER_ADMIN_SUCCESS = 'GET_ALL_VOUCHER_ADMIN_SUCCESS';
export const GET_ALL_VOUCHER_ADMIN_FAIL = 'GET_ALL_VOUCHER_ADMIN_FAIL';
export const GET_ALL_VOUCHER_ADMIN_ACCOUNT_SUCCESS =
  'GET_ALL_VOUCHER_ADMIN_ACCOUNT_SUCCESS';
export const GET_ALL_VOUCHER_ADMIN_ACCOUNT_FAIL =
  'GET_ALL_VOUCHER_ADMIN_ACCOUNT_FAIL';
export const GET_VOUCHER_PAGE_SUCCESS = 'GET_VOUCHER_PAGE_SUCCESS';
export const GET_VOUCHER_PAGE_FAIL = 'GET_VOUCHER_PAGE_FAIL';
export const GET_VOUCHER_DETAIL_SUCCESS = 'GET_VOUCHER_DETAIL_SUCCESS';
export const GET_VOUCHER_DETAIL_FAIL = 'GET_VOUCHER_DETAIL_FAIL';
export const SEARCH_VOUCHER_SUCCESS = 'SEARCH_VOUCHER_SUCCESS';
export const SEARCH_VOUCHER_FAIL = 'SEARCH_VOUCHER_FAIL';
export const POST_VOUCHER_SUCCESS = 'POST_VOUCHER_SUCCESS';
export const POST_VOUCHER_FAIL = 'POST_VOUCHER_FAIL';
export const PUT_VOUCHER_SUCCESS = 'PUT_VOUCHER_SUCCESS';
export const PUT_VOUCHER_FAIL = 'PUT_VOUCHER_FAIL';
export const DELETE_VOUCHER_SUCCESS = 'DELETE_VOUCHER_SUCCESS';
export const DELETE_VOUCHER_FAIL = 'DELETE_VOUCHER_FAIL';
export const CLOSE_VOUCHER = 'CLOSE_VOUCHER';
